CREATE TABLE Users (
    UserID INTEGER PRIMARY KEY,
    UserName TEXT  NOT NULL
);

CREATE TABLE Groups (
    GroupID INTEGER PRIMARY KEY,
    GroupName TEXT  NOT NULL
);

CREATE TABLE GroupMember (
    GroupID INTEGER,   
    UserID INTEGER,   
    PRIMARY KEY (GroupID , UserID),
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE RESTRICT
);

CREATE TABLE Expense (
	ExpenseID INTEGER PRIMARY KEY,
	Amount INTEGER NOT NULL CHECK (Amount > 0),
	Description TEXT NOT NULL,
	PaidByUserID INTEGER NOT NULL,
	GroupID INTEGER,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PaidByUserID) REFERENCES Users(UserID) ON DELETE RESTRICT,
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID) ON DELETE CASCADE
);

CREATE TABLE Split (
    ExpenseID INTEGER,
	UserID INTEGER,
	Amount INTEGER NOT NULL CHECK (Amount > 0),
    PRIMARY KEY (ExpenseID, UserID),
	Settled BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (ExpenseID) REFERENCES Expense(ExpenseID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE RESTRICT
);

