CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY,
    UserName TEXT  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Groups (
    GroupID INTEGER PRIMARY KEY,
    GroupName TEXT  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS GroupMembers (
    GroupID INTEGER,   
    UserID INTEGER,   
    PRIMARY KEY (GroupID , UserID),
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Expenses (
	ExpenseID INTEGER PRIMARY KEY,
	Amount INTEGER NOT NULL CHECK (Amount > 0),
	Description TEXT NOT NULL,
	PaidByUserID INTEGER NOT NULL,
	GroupID INTEGER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PaidByUserID) REFERENCES Users(UserID) ON DELETE RESTRICT,
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Splits (
    ExpenseID INTEGER,
	UserID INTEGER,
	Amount INTEGER NOT NULL CHECK (Amount > 0),
	Settled BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (ExpenseID, UserID),
    FOREIGN KEY (ExpenseID) REFERENCES Expenses(ExpenseID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_expenses_group ON Expenses(GroupID);
CREATE INDEX IF NOT EXISTS idx_expenses_paid_by ON Expenses(PaidByUserID);
CREATE INDEX IF NOT EXISTS idx_groupmembers_user ON GroupMembers(UserID);
CREATE INDEX IF NOT EXISTS idx_splits_user ON Splits(UserID);